export const pdfStyles = {
    // Force all colors to be hex/rgba to avoid lab/oklch issues with html2canvas
    "--background": "#ffffff",
    "--foreground": "#09090b",
    "--card": "#ffffff",
    "--card-foreground": "#09090b",
    "--popover": "#ffffff",
    "--popover-foreground": "#09090b",
    "--primary": "#18181b",
    "--primary-foreground": "#fafafa",
    "--secondary": "#f4f4f5",
    "--secondary-foreground": "#18181b",
    "--muted": "#f4f4f5",
    "--muted-foreground": "#71717a",
    "--accent": "#f4f4f5",
    "--accent-foreground": "#18181b",
    "--destructive": "#ef4444",
    "--border": "#e4e4e7",
    "--input": "#e4e4e7",
    "--ring": "#a1a1aa",
    "--chart-1": "#e86e30",
    "--chart-2": "#2a9d8f",
    "--chart-3": "#264653",
    "--chart-4": "#f4a261",
    "--chart-5": "#e76f51",
    "--sidebar": "#ffffff",
    "--sidebar-foreground": "#09090b",
    "--sidebar-primary": "#18181b",
    "--sidebar-primary-foreground": "#fafafa",
    "--sidebar-accent": "#f4f4f5",
    "--sidebar-accent-foreground": "#18181b",
    "--sidebar-border": "#e4e4e7",
    "--sidebar-ring": "#a1a1aa",
    // Additional properties to ensure all colors are compatible
    "--radius": "0.625rem",
    // Force color-scheme to light to avoid any dark mode color transformations
    "colorScheme": "light",
} as React.CSSProperties

