import type { Metadata } from "next";
import "./globals.css";
import { AuthListener } from "@/components/auth/AuthListener";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <AuthListener />
        {children}
      </body>
    </html>
  );
}
