import type { Metadata } from "next";
import { Montserrat_Alternates, Poppins } from "next/font/google";
import "./globals.css";
import { AuthListener } from "@/components/auth/AuthListener";

const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat-alternates",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserratAlternates.variable} ${poppins.variable}`}>
      <body className="antialiased font-sans">
        <AuthListener />
        {children}
      </body>
    </html>
  );
}
